name: CI Build and Test

on:
  workflow_call:
  pull_request:
    branches: ['master','dockerfile']

concurrency:
  # Cancel in-progress runs on PR update
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build & run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
          cache: true

      - name: Install dependencies
        run: go get ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Arch-Go
        run: go run main.go -v --html

      - uses: actions/upload-artifact@v3
        with:
          name: Arch-Go Report
          path: .arch-go/report.html