name: Default Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Arch-Go
        run: |
          # Define convenience function
          function runTest() {
              echo -e "\e[34m++++++++++++++++++++++++++++++++++++++++\n\e[34m+ Run test: $1\n\e[34m++++++++++++++++++++++++++++++++++++++++\e[0m"
              bash -c "$1"
          }

          # Run tests
          runTest "go run main.go describe"
          runTest "go run main.go describe -v"
          runTest "go run main.go"
          runTest "go run main.go -v"
          runTest "go run main.go -v --html"
          runTest "go run main.go -v --html --color no"
          runTest "go run main.go --verbose --html --color yes"
          runTest "go run main.go --html --color yes"

      - uses: actions/upload-artifact@v2
        with:
          name: Arch-Go Report
          path: .arch-go/report.html
